## https://alphaparticle.com/blog/automating-ftp-deployments-with-github-actions/
name: Production Deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node: [16]
        
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2 
        
    - name: Setup node env
      uses: actions/setup-node@v3.0.0
      with:
        node-version: ${{ matrix.node }}
        
    - name: Install NPM packages
      run: npm install

    - name: Build Nuxt
      run: npm run build
    
    - name: Generate Nuxt
      run: npm run generate
      
    - name: Show File Structure
      run: pwd && ls -la && cd dist && ls -la
      
    - name: FTP Deploy to WP Engine (Staging)
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.SERVER }} # for Mittwald using sftp://pXXXXXX.mittwaldserver.info:22
        ftp-username: ${{ secrets.USERNAME }} # create custom sftp account
        ftp-password: ${{ secrets.PASSWORD }} # set special password for custom sftp account
        local-dir: /home/runner/work/loproku/loproku/dist # set directory for deployment
        git-ftp-args: --insecure # if your certificate is setup correctly this can be removed (see known-hosts argument)
